# Generated by Django 3.0.7 on 2020-11-12 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MasterTendik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departemen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Departemen')),
            ],
        ),
        migrations.CreateModel(
            name='MasterMahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('NRP', models.CharField(max_length=14, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departemen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Departemen')),
            ],
        ),
        migrations.CreateModel(
            name='MasterDosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('NIP', models.CharField(max_length=32, unique=True)),
                ('golongan', models.CharField(blank=True, max_length=20)),
                ('jabatan_fungsional', models.CharField(max_length=100)),
                ('pendidikan_tertinggi', models.CharField(max_length=100)),
                ('ijazah', models.CharField(blank=True, max_length=100)),
                ('jabatan', models.CharField(blank=True, max_length=100, null=True)),
                ('status_kepegawaian', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departemen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Departemen')),
            ],
        ),
    ]
