# Generated by Django 3.0.7 on 2020-12-06 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_auto_20200721_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdosen',
            name='departemen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.Departemen'),
        ),
        migrations.AlterField(
            model_name='masterdosen',
            name='jabatan_fungsional',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='masterdosen',
            name='pendidikan_tertinggi',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
