# Generated by Django 3.0.7 on 2020-12-06 02:17

from django.db import migrations
from django.contrib.auth.hashers import make_password
import pandas as pd
import numpy as np

def master_dosen_seed(apps, schema_editor):
    df = pd.read_excel('data/911636_Daftar_20Dosen_20FTEIC_20versiKP.xlsx', sheet_name=0)
    df = df.drop(df.columns[[0, 4, 5, 6, 10]], axis=1)
    df = df.drop([0, 1, 2])
    df = df.replace(np.nan, '', regex=True)
    df.columns = ['nama', 'NIP', 'golongan', 'jabatan_fungsional', 'pendidikan_tertinggi', 'ijazah', 'departemen', 'jabatan', 'status_kepegawaian']
    df = df.astype(str)

    User = apps.get_model('authentication', 'User')
    MasterDosen = apps.get_model('masters', 'MasterDosen')
    Departemen = apps.get_model('masters', 'Departemen')

    for _, row in df.iterrows():
        try:
            departemen = Departemen.objects.get(nama=row.departemen)
        except:
            departemen = None

        NIP = row.NIP.replace(' ', '')

        dosen = MasterDosen(
            nama=row.nama, 
            NIP=NIP, 
            golongan=row.golongan, 
            jabatan_fungsional=row.jabatan_fungsional,
            ijazah=row.ijazah,
            departemen=departemen,
            jabatan=row.jabatan,
            status_kepegawaian=row.status_kepegawaian
        )
        dosen.save()

        user = User(username=NIP, dosen=dosen)
        user.password = make_password(NIP)
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_auto_20201206_0916'),
    ]

    operations = [
        migrations.RunPython(master_dosen_seed)
    ]
