# Generated by Django 3.0.7 on 2020-07-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KuliahTamu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topik', models.CharField(max_length=255)),
                ('pemateri', models.TextField()),
                ('institusi', models.CharField(max_length=255)),
                ('tingkat', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('filepath', models.FileField(upload_to='kuliahtamu/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
