# Generated by Django 3.0.7 on 2020-07-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Konferensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('author', models.TextField()),
                ('published_at', models.TextField()),
                ('url', models.CharField(max_length=255)),
                ('tahun', models.CharField(max_length=4)),
                ('tingkat', models.CharField(max_length=50)),
                ('pi', models.SmallIntegerField()),
                ('pn', models.SmallIntegerField()),
                ('konf_hal', models.CharField(max_length=255)),
                ('tempat', models.CharField(max_length=255)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
