# Generated by Django 3.0.7 on 2020-10-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konferensi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='konferensi',
            name='scopus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='konferensi',
            name='pi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='konferensi',
            name='pn',
            field=models.BooleanField(default=False),
        ),
    ]
