# Generated by Django 3.0.7 on 2020-11-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konferensi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='konferensi',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
