# Generated by Django 3.0.7 on 2020-11-12 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KuliahTamu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topik', models.CharField(max_length=255)),
                ('pemateri', models.TextField()),
                ('institusi', models.CharField(max_length=255)),
                ('tingkat', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('filepath', models.FileField(upload_to='kuliahtamu/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('departemen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masters.Departemen')),
            ],
        ),
    ]
