# Generated by Django 3.0.7 on 2020-11-10 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_auto_20200723_1419'),
        ('kuliahtamu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuliahtamu',
            name='departemen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masters.Departemen'),
        ),
    ]
