# Generated by Django 3.0.7 on 2020-11-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuliahtamu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuliahtamu',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
