# Generated by Django 3.0.7 on 2020-11-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuliahtamu', '0003_auto_20201113_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuliahtamu',
            name='filepath',
            field=models.FileField(null=True, upload_to='kuliahtamu/'),
        ),
    ]
