# Generated by Django 3.0.7 on 2020-12-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuliahtamu', '0004_auto_20201119_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuliahtamu',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
