# Generated by Django 3.0.7 on 2020-11-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestasi', '0002_auto_20201119_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestasi',
            name='jenis',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
