# Generated by Django 3.0.7 on 2020-11-20 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_auto_20200721_0309'),
        ('prestasi', '0003_prestasi_jenis'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestasi',
            name='departemen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masters.Departemen'),
        ),
    ]
