# Generated by Django 3.0.7 on 2020-12-04 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_auto_20200721_0309'),
        ('sertifikasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sertifikasi',
            name='departemen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masters.Departemen'),
        ),
        migrations.AlterField(
            model_name='sertifikasi',
            name='filepath',
            field=models.FileField(null=True, upload_to='sertifikasi/'),
        ),
    ]
