# Generated by Django 3.0.7 on 2020-11-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_training_jenis'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
