# Generated by Django 3.0.7 on 2020-09-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurnal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('published_at', models.TextField()),
                ('jurnal_vol', models.CharField(max_length=100)),
                ('jurnal_no', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('tahun', models.CharField(max_length=4)),
                ('tingkat', models.CharField(max_length=50)),
                ('pi', models.SmallIntegerField()),
                ('pn', models.SmallIntegerField()),
                ('jurnalnasional', models.SmallIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
