# Generated by Django 3.0.7 on 2020-10-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0002_auto_20201009_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnal',
            name='scopus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jurnal',
            name='pi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jurnal',
            name='pn',
            field=models.BooleanField(default=False),
        ),
    ]
